### ISSUE TITLE
Unable to read keystore JSON: "unknown field `description` using sigp/lighthouse:medalla

### ISSUE THREAD

**Issue by mgcrea** [sigp/lighthouse#1406]
## Description

Was trying to import validator keys created with [eth2.0-deposit-cli](https://github.com/ethereum/eth2.0-deposit-cli), using the `sigp/lighthouse:medalla` docker image.

Using command:

```
docker run -it --rm -v $HOME/.lighthouse:/root/.lighthouse -v $HOME/validator_keys/:/tmp/validator_keys sigp/lighthouse:medalla lighthouse account_manager validator import --directory /tmp/validator_keys
```

Actual keys in file:

```
# cat validator_keys/keystore-m_12381_3600_0_0_0-1595870942.json | jq 'keys'
[
  "crypto",
  "description",
  "path",
  "pubkey",
  "uuid",
  "version"
]
```

## Version

Using current [sigp/lighthouse:medalla](https://hub.docker.com/layers/sigp/lighthouse/medalla/images/sha256-8ace8fd98546e3d443cd7548003cecd490f1907ad99ff0d476c7219d538e4ba4?context=explore) image (digest: `8ace8fd98546`)

keystore file has `"version": 4`.

## Present Behaviour

> Unable to read keystore JSON "/tmp/validator_keys/keystore-m_12381_3600_0_0_0-1595870942.json": ReadError("unknown field `description`, expected one of `crypto`, `uuid`, `path`, `pubkey`, `version` at line 1 column 504")

## Expected Behaviour

Properly import keystore

## Steps to resolve

Probably handle/ignore the extraneous new `description` field.

**Comment by pawanjay176** [comment]
Hey @mgcrea , we have fixed that issue in the medalla branch but haven't updated the docker image yet. Should be updated soon.

**Comment by AgeManning** [comment]
Resolved in #1381

**Comment by mgcrea** [comment]
Any idea when the working docker image might be released? I'm still encountering this issue with the latest image:

```
Digest: sha256:8ace8fd98546e3d443cd7548003cecd490f1907ad99ff0d476c7219d538e4ba4
Status: Downloaded newer image for sigp/lighthouse:medalla
docker.io/sigp/lighthouse:medalla
```

**Comment by michaelsproul** [comment]
Hi @mgcrea, the `sigp/lighthouse:latest` image will now work with Medalla, so if you pull that it should work. Sorry, we announced the deprecation of the `:medalla` tag on Discord, but I'm aware that not everyone is on there. Let us know if that works for you

**Comment by mgcrea** [comment]
@michaelsproul yep thanks, does work.

**Comment by michaelsproul** [comment]
Awesome! Good to hear!
