### ISSUE TITLE
Missing `version` in response of Beacon-API method `getPendingConsolidations`

### ISSUE THREAD

**Issue by Alleysira** [sigp/lighthouse#7440]
#### Overview

Hello developers.

I am conducting API testing on a Electra PoS devnet chain and noticed inconsistencies in the JSON-RPC responses among Prysm, Lighthouse(v7.0.1-e42406d/x86_64-linux), Nimbus, and Teku. 

In particular, the `/eth/v1/beacon/states/{state_id}/pending_consolidations` endpoint returns a truncated response from Lighthouse, which includes only the `data`,`execution_optimistic` and `finalized` field, whereas the `version` field as required in the spec at [`beacon-api`](https://ethereum.github.io/beacon-APIs/#/Beacon/getPendingConsolidations).

Thanks for your time.

#### Reproduce

1. Platform details (OS, architecture): Ubuntu 20.04, x86-64
2. Branch/commit used: `v7.0.1-e42406d/x86_64-linux` with geth/besu/nethermind/reth.
3. Commands being executed: I think the minimal repro is

```
curl -X GET 'http://localhost:4000/eth/v1/beacon/states/head/pending_consolidations' -H 'accept: application/json'
```

Results

```json
# lighthouse response
{"data": [], "execution_optimistic": false, "finalized": false}
# expected
{"data": [], "execution_optimistic": false, "finalized": false, "version": "electra"}
```

**Comment by michaelsproul** [comment]
Thanks for the report!

We noticed this recently as well and I think it is fixed as part of this PR:

- https://github.com/sigp/lighthouse/pull/7372

The patch will be in v7.1.0

**Comment by Alleysira** [comment]
> The patch will be in v7.1.0

Sorry for discussing in a closed issue. 

But I noticed that this is still not fixed in `Lighthouse/v8.0.0-rc.1-1fb94ce/x86_64-linux`. Other CL clients do not have this issue.

```
# lighthouse
{"data": [], "execution_optimistic": false, "finalized": true}
# prysm
{"data": [], "execution_optimistic": false, "finalized": false, "version": "electra"}
# teku
{"data": [], "execution_optimistic": false, "finalized": true, "version": "electra"}
# nimbus
{"data": [], "execution_optimistic": false, "finalized": true, "version": "electra"}
# lodestar
{"data": [], "execution_optimistic": false, "finalized": true, "version": "electra"}
# grandine
{"data": [], "execution_optimistic": false, "finalized": false, "version": "electra"}
```

**Comment by michaelsproul** [comment]
Thanks for the pick up @Alleysira. Sorry that we dropped the ball on this. We'll try to get this in for v8.0.0-rc.2, although the timeline is quite tight.

**Comment by jimmygchen** [comment]
Fixed in #8251
